export const CLEAN_CHARACTER_DETAIL = "CREATE_CHARACTER_DETAIL";
export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const GET_CHARACTER_BY_ID = 'GET_CHARACTER_BY_ID'
export const GET_CHARACTER_DETAIL = 'GET_CHARACTERS_DETAIL'
